//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/PrototipadoJon/MiniJuegoLaser/Inputs/LaserControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @LaserControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @LaserControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""LaserControls"",
    ""maps"": [
        {
            ""name"": ""Laser"",
            ""id"": ""777fbe4e-46b9-4ccd-8087-d6b77fbd6455"",
            ""actions"": [
                {
                    ""name"": ""Space"",
                    ""type"": ""Button"",
                    ""id"": ""c6f17311-7f14-444b-8dd7-1875b5997c9f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dccd4696-cc6f-4a3a-912c-ef3445ccee11"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Laser
        m_Laser = asset.FindActionMap("Laser", throwIfNotFound: true);
        m_Laser_Space = m_Laser.FindAction("Space", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Laser
    private readonly InputActionMap m_Laser;
    private List<ILaserActions> m_LaserActionsCallbackInterfaces = new List<ILaserActions>();
    private readonly InputAction m_Laser_Space;
    public struct LaserActions
    {
        private @LaserControls m_Wrapper;
        public LaserActions(@LaserControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Space => m_Wrapper.m_Laser_Space;
        public InputActionMap Get() { return m_Wrapper.m_Laser; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LaserActions set) { return set.Get(); }
        public void AddCallbacks(ILaserActions instance)
        {
            if (instance == null || m_Wrapper.m_LaserActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LaserActionsCallbackInterfaces.Add(instance);
            @Space.started += instance.OnSpace;
            @Space.performed += instance.OnSpace;
            @Space.canceled += instance.OnSpace;
        }

        private void UnregisterCallbacks(ILaserActions instance)
        {
            @Space.started -= instance.OnSpace;
            @Space.performed -= instance.OnSpace;
            @Space.canceled -= instance.OnSpace;
        }

        public void RemoveCallbacks(ILaserActions instance)
        {
            if (m_Wrapper.m_LaserActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILaserActions instance)
        {
            foreach (var item in m_Wrapper.m_LaserActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LaserActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LaserActions @Laser => new LaserActions(this);
    public interface ILaserActions
    {
        void OnSpace(InputAction.CallbackContext context);
    }
}
